models.py
import re
from datetime import datetime

from sqlalchemy.orm import backref

from app import db

from flask_security import UserMixin, RoleMixin


def slugife(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')))


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugife(self.title)

    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugife(self.name)

    def __repr__(self):
        return f'<Tag id: {self.id}, name: {self.name}'


roles_users = db.Table('roles_users',
                     db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('role_id', db.Integer, db.ForeignKey('role.id')))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask, redirect, url_for, request
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

from models import Post, Tag, User, Role


class AdminMixin:
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', newt=request.url))


class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)


class AdminView(AdminMixin, ModelView):
    pass


class HomeAdminView(AdminMixin, AdminIndexView):
    pass


class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body']


class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name']


admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from posts.blueprint import posts
import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, redirect, url_for
from flask import request
from flask_security import login_required
from models import Post, Tag

from app import db
from .forms import PostForm

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Error create Post')
        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
         page = 1
    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())
    pages = posts.paginate(page=page, per_page=3)
    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    return render_template('posts/detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    Create new post
{% endblock %}

{% block content %}
<div class="col-md-10">
    <form action="{{ url_for('posts.create_post')}}" method="post">
        {% for field in form %}
        <div class="form-group">
            {{field.label(class='control-label')}}
            {{field(class='form-control')}}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
    {{post.title}}
{% endblock %}

{% block content_title %}
    {{post.title}}
{% endblock %}

{% block content %}
    <div class="tags">
        {% for tag in tags %}
            <a href="{{  url_for('posts.tag_detail', slug=tag.slug)   }}">
                <span class="badge badge-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>

    <p>{{post.title}}</p>
    <p>{{post.body}}</p>
    <p>{{post.created}}</p>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{% block content %}
<div class="col-md-10">
    <form action="{{ url_for('posts.edit_post', slug=post.slug)}}" method="post">
        {% for field in form %}
        <div class="form-group">
            {{field.label(class='control-label')}}
            {{field(class='form-control')}}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Edit</button>
    </form>
</div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index page
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in pages.items %}
       <p>
           <a href="{{  url_for('posts.post_detail', slug=post.slug)   }}">{{ post.title }}</a>
       </p>
    {% endfor %}
    <nav>
      <ul class="pagination">
        <li {% if not pages.has_prev %} class="page-item disabled" {% endif %}>
          <a class="page-link" href="?page={{ pages.prev_num }}" tabindex="-1">Previous</a>
        </li>
<!--        {% if pages.has_prev %}-->
<!--            <li class="page-item"><a class="page-link" href="./?page={{ pages.prev_num }}">{{ pages.prev_num }}</a></li>-->
<!--        {% endif %}-->
        {% for page in pages.iter_pages(left_edge=1, left_current=2, right_current=2, right_edge=1) %}
            {% if page %}
            <li {% if page == pages.page %} class="page-item active" {% endif %}>
                <a class="page-link" href="?page={{ page }}">{{ page }} <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" >...<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        {% endfor %}
<!--        {% if pages.has_next %}-->
<!--            <li class="page-item"><a class="page-link" href="./?page={{ pages.next_num }}">{{ pages.next_num }}</a></li>-->
<!--        {% endif %}-->
        <li {% if not pages.has_next %} class="page-item disabled" {% endif %}>
          <a class="page-link" href="?page={{ pages.next_num }}">Next</a>
        </li>
      </ul>
    </nav>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{tag.name}}
{% endblock %}

{% block content_title %}
    {{tag.name}}
{% endblock %}

{% block content %}
    <span class="badge badge-primary">{{ tag.name }}</span>
    <div class="tags">
        {% for post in posts %}
            <p>
                <a href="{{  url_for('posts.post_detail', slug=post.slug)   }}">{{ post.title }}</a>
            </p>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('index') }}">Flask <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.index') }}">Blog</a>
            </li>
            {% if current_user.has_role('admin') %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.create_post') }}" >New Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin" >Admin</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                    name="q" value="{{ request.args.get('q', '') }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<div class="container">
    <h3>
        {% block content_title %}
        {% endblock %}

    </h3>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Index page
{% endblock %}

{% block content %}
    Some content
{% endblock %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-offset-3 col-md-6">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <h1>{{ _('Login') }}</h1>
    <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        {{ render_field_with_errors(login_user_form.email, class='form-control') }}
        {{ render_field_with_errors(login_user_form.password, class='form-control') }}
        {{ render_field_with_errors(login_user_form.remember) }}
        {{ render_field(login_user_form.next) }}
        {{ render_field(login_user_form.submit, class='btn btn-success') }}
    </form>
    {% include "security/_menu.html" %}
</div>
{% endblock %}